### ISSUE TITLE
每次戴上或者戴不上都是玄学问题

### ISSUE THREAD

**Issue by XiaoHuiHui233** [BelowZeroKelvin/MCDR-Hat#2]
第一次输入，火把戴上头了
然后摘下来 第二次输入就报错
之后就一直报错
然后别人输入 就可以戴上 然后摘下来 然后又戴不上
戴不上的报错如下：
![11DF1134D0C3CD1741EC15F56BB2DF5A](https://user-images.githubusercontent.com/21187839/82143385-1a1ea400-9876-11ea-8090-c14db6fc2b95.jpg)

**Comment by BelowZeroKelvin** [comment]
目前测试了一下没有发现带上就报错的情况，定位不到问题
